version: '3.8'
services:
  # backend:
  #   image: sua-imagem-quarkus-app:latest  # Use a imagem Docker do seu Quarkus
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"  # Mapeia a porta 8080 do container para a porta 8080 no host
  #   environment:
  #     - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/eventsdb
  #     - QUARKUS_DATASOURCE_USERNAME=usuarioeventos
  #     - QUARKUS_DATASOURCE_PASSWORD=senhaeventos
  #     - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: usuarioeventos
      POSTGRES_PASSWORD: senhaeventos
    ports:
      - "5432:5432"  # Mapeia a porta PostgreSQL 5432 para o host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persiste dados do banco de dados

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@rafaelfreitas.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Interface web do pgAdmin disponível em localhost:5050
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data:  # Define um volume que persiste o estado do banco de dados
